controller_list:
  - name: aidplus/aidplus_left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_shoulder_joint
      - left_bigarm_joint
      - left_elbow_joint
      - left_wrist1_joint
      - left_wrist2_joint
      - left_palm_joint
  - name: aidplus/aidplus_right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_shoulder_joint
      - right_bigarm_joint
      - right_elbow_joint
      - right_wrist1_joint
      - right_wrist2_joint
      - right_palm_joint

