controller_joint_names: ['left_shoulder_joint', 'left_bigarm_joint', 'left_elbow_joint', 'left_wrist1_joint', 'left_wrist2_joint', 'left_palm_joint',
                         'right_shoulder_joint', 'right_bigarm_joint', 'right_elbow_joint', 'right_wrist1_joint', 'right_wrist2_joint', 'right_palm_joint']
robot_name: aidplus

