aidplus:
  # publish all joint states--------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Gazebo use controller that ros_control(joint_position_controller)
  # Position Controllers------------------
  aidplus_left_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - left_shoulder_joint
            - left_bigarm_joint
            - left_elbow_joint
            - left_wrist1_joint
            - left_wrist2_joint
            - left_palm_joint
        
        gains: # Required because we're controlling a velocity interface
            left_shoulder_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            left_bigarm_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14
            left_elbow_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            left_wrist1_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            left_wrist2_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            left_palm_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14
        
        constraints:
            goal_time: &goal_time_constraint 4.0
            stopped_velocity_tolerance: 0.05
            left_shoulder_Joint:
                goal: &goal_pos_constraint 0.1
                trajectory: &trajectory_pos_constraint 0.1
            left_bigarm_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            left_elbow_Joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint         
            left_wrist1_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            left_wrist2_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            left_palm_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint  
# Gazebo use controller that ros_control(joint_position_controller)
  # Position Controllers------------------
  aidplus_right_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - right_shoulder_joint
            - right_bigarm_joint
            - right_elbow_joint
            - right_wrist1_joint
            - right_wrist2_joint
            - right_palm_joint
        
        gains: # Required because we're controlling a velocity interface
            right_shoulder_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            right_bigarm_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14
            right_elbow_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            right_wrist1_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            right_wrist2_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14 
            right_palm_joint: 
                p: 18.0 
                i: 270.0
                d: 0.0001 
                i_clamp: 20.14
        
        constraints:
            goal_time: *goal_time_constraint 
            stopped_velocity_tolerance: 0.05
            right_shoulder_Joint:
                goal: *goal_pos_constraint 
                trajectory: *trajectory_pos_constraint 
            right_bigarm_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            right_elbow_Joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint         
            right_wrist1_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            right_wrist2_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint
            right_palm_joint:
                goal: *goal_pos_constraint
                trajectory: *trajectory_pos_constraint  
